name: Build and Deploy Javadoc

on:
  push:
    branches: [ "master" ] 
jobs:
  # 1) Build the Javadoc and upload as artifact
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 23

      - name: Build Javadoc
        run: |
          # Adjust according to your build system (Maven, Gradle, etc.)
          # Example with Maven:
          mvn clean install
          mvn javadoc:javadoc \
          -Dmaven.javadoc.failOnError=false \
          -Dmaven.javadoc.skip=false

      - name: Inject MathJax script
        # Adjust path to where your Javadoc output is actually generated
        run: |
          find target/site/apidocs -type f -name "*.html" -exec \
            sed -i '/<\/head>/i <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>' {} +

      - name: Upload Pages Artifact
        # This action collects the directory containing docs
        # and makes it available as an artifact for later jobs
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Path to the folder containing generated docs
          # Adjust path to match your actual Javadoc output
          path: target/reports/apidocs

  # --- 2) Deploy the artifact to GitHub Pages
  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write       # required
      id-token: write    # required
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
